# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 526b157b8e9a6f1a7abf0041828be300a656c0ae077818052a6b45485d3f6e0debe5de9151e052bb29ffda2936bca3ecd5f23900f7c1d5e20ea872d1314073a9

test:
  secret_key_base: 29cca5a96c895c7dad16e8dd47ec649cd2f11fa06cd0b1a41c790ef1bd257b21ce4828c4aa7461ea44fe195ff85185c99219ff7251f78c9b8423a9f9fd627195

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
